// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8VgXQxru1bzlbLTUvOc4o490gxDc_MDQ',
    appId: '1:209940213885:web:1b68309df786c4c30fc114',
    messagingSenderId: '209940213885',
    projectId: 'cloudsense-cba8a',
    authDomain: 'cloudsense-cba8a.firebaseapp.com',
    storageBucket: 'cloudsense-cba8a.firebasestorage.app',
    measurementId: 'G-HMXS0HV32J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoa9Y1-YvL85Q_1Br580SsrgDjRRO_kYk',
    appId: '1:209940213885:android:644c0bd5faefaadc0fc114',
    messagingSenderId: '209940213885',
    projectId: 'cloudsense-cba8a',
    storageBucket: 'cloudsense-cba8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrAo8MFPbKhocMEswkRQVEAO-GYKJIes',
    appId: '1:209940213885:ios:e77c80bce35393930fc114',
    messagingSenderId: '209940213885',
    projectId: 'cloudsense-cba8a',
    storageBucket: 'cloudsense-cba8a.firebasestorage.app',
    iosBundleId: 'com.awadh.CloudSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUrAo8MFPbKhocMEswkRQVEAO-GYKJIes',
    appId: '1:209940213885:ios:e77c80bce35393930fc114',
    messagingSenderId: '209940213885',
    projectId: 'cloudsense-cba8a',
    storageBucket: 'cloudsense-cba8a.firebasestorage.app',
    iosBundleId: 'com.awadh.CloudSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8VgXQxru1bzlbLTUvOc4o490gxDc_MDQ',
    appId: '1:209940213885:web:eb680305c051412c0fc114',
    messagingSenderId: '209940213885',
    projectId: 'cloudsense-cba8a',
    authDomain: 'cloudsense-cba8a.firebaseapp.com',
    storageBucket: 'cloudsense-cba8a.firebasestorage.app',
    measurementId: 'G-0RDKYRM5BL',
  );
}
