# Flutter Proguard Rules
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.amplifyframework.** { *; }
-dontwarn io.flutter.embedding.**
-dontwarn com.google.firebase.**
-dontwarn com.amplifyframework.**
